// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type QuestionVersion struct {
	ID                  string             `json:"id"`
	QuestionID          string             `json:"question_id"`
	Version             int32              `json:"version"`
	Prompt              string             `json:"prompt"`
	ConfiguredReference string             `json:"configured_reference"`
	ExpectedEvidence    string             `json:"expected_evidence"`
	CreatedBySubjectID  string             `json:"created_by_subject_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type RegulatoryReferenceVersion struct {
	ID            string             `json:"id"`
	ReferenceID   string             `json:"reference_id"`
	Version       int32              `json:"version"`
	Title         string             `json:"title"`
	Status        string             `json:"status"`
	EffectiveDate pgtype.Date        `json:"effective_date"`
	Snapshot      []byte             `json:"snapshot"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ReportDefinitionVersion struct {
	ID                 string             `json:"id"`
	DefinitionID       string             `json:"definition_id"`
	Version            int32              `json:"version"`
	Title              string             `json:"title"`
	Description        string             `json:"description"`
	Definition         []byte             `json:"definition"`
	CreatedBySubjectID string             `json:"created_by_subject_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type TemplateVersionQuestion struct {
	TemplateVersionID string             `json:"template_version_id"`
	QuestionVersionID string             `json:"question_version_id"`
	Position          int32              `json:"position"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type UserLifecycleRequest struct {
	ID                      string             `json:"id"`
	SubjectID               *string            `json:"subject_id"`
	RequestedAction         string             `json:"requested_action"`
	RequestedRoles          []string           `json:"requested_roles"`
	RequestedOrganizationID *string            `json:"requested_organization_id"`
	Status                  string             `json:"status"`
	IdempotencyKey          string             `json:"idempotency_key"`
	RequestedBySubjectID    string             `json:"requested_by_subject_id"`
	OutboxMessageID         *string            `json:"outbox_message_id"`
	FailureReason           *string            `json:"failure_reason"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}
