// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthorizedSyncChange struct {
	SequenceID     int64              `json:"sequence_id"`
	SubjectID      string             `json:"subject_id"`
	OrganizationID *string            `json:"organization_id"`
	PackageID      *string            `json:"package_id"`
	Kind           string             `json:"kind"`
	EntityID       string             `json:"entity_id"`
	EntityRevision *int64             `json:"entity_revision"`
	Payload        []byte             `json:"payload"`
	ChangedAt      pgtype.Timestamptz `json:"changed_at"`
}

type OfflineGrant struct {
	ID                  string             `json:"id"`
	SubjectID           string             `json:"subject_id"`
	DeviceID            string             `json:"device_id"`
	PackageID           string             `json:"package_id"`
	InspectionID        string             `json:"inspection_id"`
	AssignmentRevision  int64              `json:"assignment_revision"`
	GrantedAt           pgtype.Timestamptz `json:"granted_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason        *string            `json:"revoke_reason"`
	SessionID           *string            `json:"session_id"`
	PackageVersion      *int32             `json:"package_version"`
	PackageDigest       *string            `json:"package_digest"`
	AllowedCommandTypes []string           `json:"allowed_command_types"`
	AssignmentScope     []byte             `json:"assignment_scope"`
	ProtocolVersion     int32              `json:"protocol_version"`
	GrantTokenHash      *string            `json:"grant_token_hash"`
}
