// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"
)

const getOfflineGrant = `-- name: GetOfflineGrant :one
SELECT id, subject_id, device_id, package_id, inspection_id, assignment_revision, granted_at,
       expires_at, revoked_at, revoke_reason, session_id, package_version, package_digest,
       allowed_command_types, assignment_scope, protocol_version, grant_token_hash
FROM offline_grants
WHERE id = $1
`

func (q *Queries) GetOfflineGrant(ctx context.Context, id string) (OfflineGrant, error) {
	row := q.db.QueryRow(ctx, getOfflineGrant, id)
	var i OfflineGrant
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.DeviceID,
		&i.PackageID,
		&i.InspectionID,
		&i.AssignmentRevision,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.SessionID,
		&i.PackageVersion,
		&i.PackageDigest,
		&i.AllowedCommandTypes,
		&i.AssignmentScope,
		&i.ProtocolVersion,
		&i.GrantTokenHash,
	)
	return i, err
}

const listAuthorizedChanges = `-- name: ListAuthorizedChanges :many
SELECT sequence_id, subject_id, organization_id, package_id, kind, entity_id, entity_revision,
       payload, changed_at
FROM authorized_sync_changes
WHERE subject_id = $1 AND sequence_id > $2
ORDER BY sequence_id
LIMIT $3
`

type ListAuthorizedChangesParams struct {
	SubjectID  string `json:"subject_id"`
	SequenceID int64  `json:"sequence_id"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) ListAuthorizedChanges(ctx context.Context, arg ListAuthorizedChangesParams) ([]AuthorizedSyncChange, error) {
	rows, err := q.db.Query(ctx, listAuthorizedChanges, arg.SubjectID, arg.SequenceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorizedSyncChange
	for rows.Next() {
		var i AuthorizedSyncChange
		if err := rows.Scan(
			&i.SequenceID,
			&i.SubjectID,
			&i.OrganizationID,
			&i.PackageID,
			&i.Kind,
			&i.EntityID,
			&i.EntityRevision,
			&i.Payload,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
