// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetOfflineGrant(ctx context.Context, id string) (OfflineGrant, error)
	ListAuthorizedChanges(ctx context.Context, arg ListAuthorizedChangesParams) ([]AuthorizedSyncChange, error)
}

var _ Querier = (*Queries)(nil)
