// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inspection struct {
	ID                         string             `json:"id"`
	OrganizationID             string             `json:"organization_id"`
	AssignedInspectorSubjectID *string            `json:"assigned_inspector_subject_id"`
	Title                      string             `json:"title"`
	InspectionType             string             `json:"inspection_type"`
	Status                     string             `json:"status"`
	DueDate                    pgtype.Date        `json:"due_date"`
	Revision                   int64              `json:"revision"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}
