// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"
)

const getInspection = `-- name: GetInspection :one
SELECT
    id,
    organization_id,
    assigned_inspector_subject_id,
    title,
    inspection_type,
    status,
    due_date,
    revision,
    created_at,
    updated_at
FROM inspections
WHERE id = $1
`

func (q *Queries) GetInspection(ctx context.Context, id string) (Inspection, error) {
	row := q.db.QueryRow(ctx, getInspection, id)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AssignedInspectorSubjectID,
		&i.Title,
		&i.InspectionType,
		&i.Status,
		&i.DueDate,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssignedInspections = `-- name: ListAssignedInspections :many
SELECT
    id,
    organization_id,
    assigned_inspector_subject_id,
    title,
    inspection_type,
    status,
    due_date,
    revision,
    created_at,
    updated_at
FROM inspections
WHERE assigned_inspector_subject_id = $1
ORDER BY due_date NULLS LAST, id
LIMIT $2
`

type ListAssignedInspectionsParams struct {
	AssignedInspectorSubjectID *string `json:"assigned_inspector_subject_id"`
	Limit                      int32   `json:"limit"`
}

func (q *Queries) ListAssignedInspections(ctx context.Context, arg ListAssignedInspectionsParams) ([]Inspection, error) {
	rows, err := q.db.Query(ctx, listAssignedInspections, arg.AssignedInspectorSubjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inspection
	for rows.Next() {
		var i Inspection
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.AssignedInspectorSubjectID,
			&i.Title,
			&i.InspectionType,
			&i.Status,
			&i.DueDate,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
