// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetInspection(ctx context.Context, id string) (Inspection, error)
	ListAssignedInspections(ctx context.Context, arg ListAssignedInspectionsParams) ([]Inspection, error)
}

var _ Querier = (*Queries)(nil)
