// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	SequenceID     int64              `json:"sequence_id"`
	EventID        string             `json:"event_id"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	ActorSubjectID *string            `json:"actor_subject_id"`
	ActorRole      *string            `json:"actor_role"`
	OrganizationID *string            `json:"organization_id"`
	Action         string             `json:"action"`
	EntityType     string             `json:"entity_type"`
	EntityID       string             `json:"entity_id"`
	RequestID      *string            `json:"request_id"`
	Details        []byte             `json:"details"`
}

type AuthorizedSyncChange struct {
	SequenceID     int64              `json:"sequence_id"`
	SubjectID      string             `json:"subject_id"`
	OrganizationID *string            `json:"organization_id"`
	PackageID      *string            `json:"package_id"`
	Kind           string             `json:"kind"`
	EntityID       string             `json:"entity_id"`
	EntityRevision *int64             `json:"entity_revision"`
	Payload        []byte             `json:"payload"`
	ChangedAt      pgtype.Timestamptz `json:"changed_at"`
}

type CapRevision struct {
	ID                   string             `json:"id"`
	CapID                string             `json:"cap_id"`
	FindingID            string             `json:"finding_id"`
	OrganizationID       string             `json:"organization_id"`
	Revision             int32              `json:"revision"`
	Status               string             `json:"status"`
	RootCause            string             `json:"root_cause"`
	CorrectiveAction     string             `json:"corrective_action"`
	PreventiveAction     string             `json:"preventive_action"`
	TargetCompletionDate pgtype.Date        `json:"target_completion_date"`
	SubmittedBySubjectID string             `json:"submitted_by_subject_id"`
	SubmittedAt          pgtype.Timestamptz `json:"submitted_at"`
}

type ChecklistResponse struct {
	ID                         string             `json:"id"`
	InspectionID               string             `json:"inspection_id"`
	PackageID                  string             `json:"package_id"`
	QuestionID                 string             `json:"question_id"`
	AssignedInspectorSubjectID *string            `json:"assigned_inspector_subject_id"`
	ResponseValue              string             `json:"response_value"`
	CommentToAuditee           *string            `json:"comment_to_auditee"`
	InternalCaaNote            *string            `json:"internal_caa_note"`
	Revision                   int64              `json:"revision"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type ChecklistTemplateVersion struct {
	ID          string             `json:"id"`
	TemplateID  string             `json:"template_id"`
	Version     int32              `json:"version"`
	Title       string             `json:"title"`
	Snapshot    []byte             `json:"snapshot"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type EvidenceVersion struct {
	ID                   string             `json:"id"`
	EvidenceID           string             `json:"evidence_id"`
	FindingID            string             `json:"finding_id"`
	OrganizationID       string             `json:"organization_id"`
	Version              int32              `json:"version"`
	ObjectMetadataID     *string            `json:"object_metadata_id"`
	Filename             string             `json:"filename"`
	MediaType            string             `json:"media_type"`
	Sha256               string             `json:"sha256"`
	SizeBytes            int64              `json:"size_bytes"`
	Status               string             `json:"status"`
	SubmittedBySubjectID string             `json:"submitted_by_subject_id"`
	SubmittedAt          pgtype.Timestamptz `json:"submitted_at"`
}

type Finding struct {
	ID                 string             `json:"id"`
	Reference          string             `json:"reference"`
	PotentialFindingID *string            `json:"potential_finding_id"`
	InspectionID       string             `json:"inspection_id"`
	OrganizationID     string             `json:"organization_id"`
	Severity           string             `json:"severity"`
	Status             string             `json:"status"`
	OwnerSubjectID     *string            `json:"owner_subject_id"`
	NextAction         string             `json:"next_action"`
	DueDate            pgtype.Date        `json:"due_date"`
	ClosureBasis       *string            `json:"closure_basis"`
	ClosureReason      *string            `json:"closure_reason"`
	Revision           int64              `json:"revision"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type IdempotencyResponse struct {
	Scope           string             `json:"scope"`
	OperationID     string             `json:"operation_id"`
	SemanticHash    string             `json:"semantic_hash"`
	ResponseStatus  int32              `json:"response_status"`
	ResponseHeaders []byte             `json:"response_headers"`
	ResponseBody    []byte             `json:"response_body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type IdentityReference struct {
	SubjectID   string             `json:"subject_id"`
	Issuer      string             `json:"issuer"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Inspection struct {
	ID                         string             `json:"id"`
	OrganizationID             string             `json:"organization_id"`
	AssignedInspectorSubjectID *string            `json:"assigned_inspector_subject_id"`
	Title                      string             `json:"title"`
	InspectionType             string             `json:"inspection_type"`
	Status                     string             `json:"status"`
	DueDate                    pgtype.Date        `json:"due_date"`
	Revision                   int64              `json:"revision"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type InspectionPackage struct {
	ID                         string             `json:"id"`
	InspectionID               string             `json:"inspection_id"`
	ChecklistTemplateVersionID string             `json:"checklist_template_version_id"`
	PackageVersion             int32              `json:"package_version"`
	Snapshot                   []byte             `json:"snapshot"`
	ExpiresAt                  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt                  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
}

type ObjectMetadatum struct {
	ID                string             `json:"id"`
	AggregateType     string             `json:"aggregate_type"`
	AggregateID       string             `json:"aggregate_id"`
	ObjectKey         string             `json:"object_key"`
	Filename          string             `json:"filename"`
	DeclaredMediaType string             `json:"declared_media_type"`
	DetectedMediaType *string            `json:"detected_media_type"`
	Sha256            string             `json:"sha256"`
	SizeBytes         int64              `json:"size_bytes"`
	ScanStatus        string             `json:"scan_status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type OfflineGrant struct {
	ID                 string             `json:"id"`
	SubjectID          string             `json:"subject_id"`
	DeviceID           string             `json:"device_id"`
	PackageID          string             `json:"package_id"`
	InspectionID       string             `json:"inspection_id"`
	AssignmentRevision int64              `json:"assignment_revision"`
	GrantedAt          pgtype.Timestamptz `json:"granted_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason       *string            `json:"revoke_reason"`
}

type Organization struct {
	ID               string             `json:"id"`
	LegalName        string             `json:"legal_name"`
	OrganizationType string             `json:"organization_type"`
	Status           string             `json:"status"`
	Revision         int64              `json:"revision"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type OutboxMessage struct {
	ID            string             `json:"id"`
	Topic         string             `json:"topic"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
	ClaimedAt     pgtype.Timestamptz `json:"claimed_at"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
	AttemptCount  int32              `json:"attempt_count"`
	LastError     *string            `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PotentialFinding struct {
	ID                  string             `json:"id"`
	InspectionID        string             `json:"inspection_id"`
	ChecklistResponseID string             `json:"checklist_response_id"`
	OrganizationID      string             `json:"organization_id"`
	Status              string             `json:"status"`
	FindingBasis        string             `json:"finding_basis"`
	ExpectedEvidence    *string            `json:"expected_evidence"`
	CommentToAuditee    string             `json:"comment_to_auditee"`
	InternalCaaNote     *string            `json:"internal_caa_note"`
	ConvertedFindingID  *string            `json:"converted_finding_id"`
	Revision            int64              `json:"revision"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type ReportDecision struct {
	ID                 string             `json:"id"`
	ReportVersionID    string             `json:"report_version_id"`
	ExpectedVersion    int32              `json:"expected_version"`
	Decision           string             `json:"decision"`
	Reason             *string            `json:"reason"`
	DecidedBySubjectID string             `json:"decided_by_subject_id"`
	DecidedAt          pgtype.Timestamptz `json:"decided_at"`
}

type ReportVersion struct {
	ID           string             `json:"id"`
	ReportID     string             `json:"report_id"`
	InspectionID string             `json:"inspection_id"`
	Version      int32              `json:"version"`
	Status       string             `json:"status"`
	Snapshot     []byte             `json:"snapshot"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ReviewDecision struct {
	ID                 string             `json:"id"`
	EntityType         string             `json:"entity_type"`
	EntityID           string             `json:"entity_id"`
	ExpectedRevision   int64              `json:"expected_revision"`
	Decision           string             `json:"decision"`
	Reason             *string            `json:"reason"`
	DecidedBySubjectID string             `json:"decided_by_subject_id"`
	DecidedAt          pgtype.Timestamptz `json:"decided_at"`
}

type SessionReference struct {
	ID                string             `json:"id"`
	SubjectID         string             `json:"subject_id"`
	OrganizationID    *string            `json:"organization_id"`
	ProviderSessionID *string            `json:"provider_session_id"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type SyncCursor struct {
	SubjectID         string             `json:"subject_id"`
	DeviceID          string             `json:"device_id"`
	CursorSequence    int64              `json:"cursor_sequence"`
	ProjectionVersion int32              `json:"projection_version"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
