// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	ID               string             `json:"id"`
	LegalName        string             `json:"legal_name"`
	OrganizationType string             `json:"organization_type"`
	Status           string             `json:"status"`
	Revision         int64              `json:"revision"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
