// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetOrganization(ctx context.Context, id string) (GetOrganizationRow, error)
	ListOrganizationRegistry(ctx context.Context, arg ListOrganizationRegistryParams) ([]ListOrganizationRegistryRow, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]ListOrganizationsRow, error)
}

var _ Querier = (*Queries)(nil)
