// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationDeliveryJob struct {
	ID                 string             `json:"id"`
	NotificationID     string             `json:"notification_id"`
	RecipientSubjectID string             `json:"recipient_subject_id"`
	Channel            string             `json:"channel"`
	Status             string             `json:"status"`
	IdempotencyKey     string             `json:"idempotency_key"`
	OutboxMessageID    *string            `json:"outbox_message_id"`
	AttemptCount       int32              `json:"attempt_count"`
	LastError          *string            `json:"last_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ReminderDispatch struct {
	ID                 string             `json:"id"`
	ReminderRuleID     string             `json:"reminder_rule_id"`
	EntityType         string             `json:"entity_type"`
	EntityID           string             `json:"entity_id"`
	RecipientSubjectID string             `json:"recipient_subject_id"`
	DueDate            pgtype.Date        `json:"due_date"`
	DueState           string             `json:"due_state"`
	NotificationID     string             `json:"notification_id"`
	DispatchedAt       pgtype.Timestamptz `json:"dispatched_at"`
}
