// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notification_records (
    id, recipient_subject_id, organization_id, title, body,
    related_entity_type, related_entity_id, deduplication_key, revision,
    created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 1, $9)
RETURNING id, recipient_subject_id, organization_id, title, body,
          related_entity_type, related_entity_id, deduplication_key,
          read_at, revision, created_at
`

type CreateNotificationParams struct {
	ID                 string             `json:"id"`
	RecipientSubjectID string             `json:"recipient_subject_id"`
	OrganizationID     *string            `json:"organization_id"`
	Title              string             `json:"title"`
	Body               string             `json:"body"`
	RelatedEntityType  *string            `json:"related_entity_type"`
	RelatedEntityID    *string            `json:"related_entity_id"`
	DeduplicationKey   string             `json:"deduplication_key"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type CreateNotificationRow struct {
	ID                 string             `json:"id"`
	RecipientSubjectID string             `json:"recipient_subject_id"`
	OrganizationID     *string            `json:"organization_id"`
	Title              string             `json:"title"`
	Body               string             `json:"body"`
	RelatedEntityType  *string            `json:"related_entity_type"`
	RelatedEntityID    *string            `json:"related_entity_id"`
	DeduplicationKey   string             `json:"deduplication_key"`
	ReadAt             pgtype.Timestamptz `json:"read_at"`
	Revision           int64              `json:"revision"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (CreateNotificationRow, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.RecipientSubjectID,
		arg.OrganizationID,
		arg.Title,
		arg.Body,
		arg.RelatedEntityType,
		arg.RelatedEntityID,
		arg.DeduplicationKey,
		arg.CreatedAt,
	)
	var i CreateNotificationRow
	err := row.Scan(
		&i.ID,
		&i.RecipientSubjectID,
		&i.OrganizationID,
		&i.Title,
		&i.Body,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.DeduplicationKey,
		&i.ReadAt,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const createNotificationDeliveryJob = `-- name: CreateNotificationDeliveryJob :one
INSERT INTO notification_delivery_jobs (
    id, notification_id, recipient_subject_id, channel, status,
    idempotency_key, outbox_message_id
) VALUES ($1, $2, $3, $4, 'PENDING', $5, $6)
RETURNING id, notification_id, recipient_subject_id, channel, status,
          idempotency_key, outbox_message_id, attempt_count, last_error,
          created_at, updated_at
`

type CreateNotificationDeliveryJobParams struct {
	ID                 string  `json:"id"`
	NotificationID     string  `json:"notification_id"`
	RecipientSubjectID string  `json:"recipient_subject_id"`
	Channel            string  `json:"channel"`
	IdempotencyKey     string  `json:"idempotency_key"`
	OutboxMessageID    *string `json:"outbox_message_id"`
}

func (q *Queries) CreateNotificationDeliveryJob(ctx context.Context, arg CreateNotificationDeliveryJobParams) (NotificationDeliveryJob, error) {
	row := q.db.QueryRow(ctx, createNotificationDeliveryJob,
		arg.ID,
		arg.NotificationID,
		arg.RecipientSubjectID,
		arg.Channel,
		arg.IdempotencyKey,
		arg.OutboxMessageID,
	)
	var i NotificationDeliveryJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.RecipientSubjectID,
		&i.Channel,
		&i.Status,
		&i.IdempotencyKey,
		&i.OutboxMessageID,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReminderDispatch = `-- name: CreateReminderDispatch :one
INSERT INTO reminder_dispatches (
    id, reminder_rule_id, entity_type, entity_id, recipient_subject_id,
    due_date, due_state, notification_id, dispatched_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, reminder_rule_id, entity_type, entity_id, recipient_subject_id,
          due_date, due_state, notification_id, dispatched_at
`

type CreateReminderDispatchParams struct {
	ID                 string             `json:"id"`
	ReminderRuleID     string             `json:"reminder_rule_id"`
	EntityType         string             `json:"entity_type"`
	EntityID           string             `json:"entity_id"`
	RecipientSubjectID string             `json:"recipient_subject_id"`
	DueDate            pgtype.Date        `json:"due_date"`
	DueState           string             `json:"due_state"`
	NotificationID     string             `json:"notification_id"`
	DispatchedAt       pgtype.Timestamptz `json:"dispatched_at"`
}

func (q *Queries) CreateReminderDispatch(ctx context.Context, arg CreateReminderDispatchParams) (ReminderDispatch, error) {
	row := q.db.QueryRow(ctx, createReminderDispatch,
		arg.ID,
		arg.ReminderRuleID,
		arg.EntityType,
		arg.EntityID,
		arg.RecipientSubjectID,
		arg.DueDate,
		arg.DueState,
		arg.NotificationID,
		arg.DispatchedAt,
	)
	var i ReminderDispatch
	err := row.Scan(
		&i.ID,
		&i.ReminderRuleID,
		&i.EntityType,
		&i.EntityID,
		&i.RecipientSubjectID,
		&i.DueDate,
		&i.DueState,
		&i.NotificationID,
		&i.DispatchedAt,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, recipient_subject_id, organization_id, title, body,
       related_entity_type, related_entity_id, deduplication_key,
       read_at, revision, created_at
FROM notification_records
WHERE id = $1 AND recipient_subject_id = $2 AND tombstoned_at IS NULL
`

type GetNotificationParams struct {
	ID                 string `json:"id"`
	RecipientSubjectID string `json:"recipient_subject_id"`
}

type GetNotificationRow struct {
	ID                 string             `json:"id"`
	RecipientSubjectID string             `json:"recipient_subject_id"`
	OrganizationID     *string            `json:"organization_id"`
	Title              string             `json:"title"`
	Body               string             `json:"body"`
	RelatedEntityType  *string            `json:"related_entity_type"`
	RelatedEntityID    *string            `json:"related_entity_id"`
	DeduplicationKey   string             `json:"deduplication_key"`
	ReadAt             pgtype.Timestamptz `json:"read_at"`
	Revision           int64              `json:"revision"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetNotification(ctx context.Context, arg GetNotificationParams) (GetNotificationRow, error) {
	row := q.db.QueryRow(ctx, getNotification, arg.ID, arg.RecipientSubjectID)
	var i GetNotificationRow
	err := row.Scan(
		&i.ID,
		&i.RecipientSubjectID,
		&i.OrganizationID,
		&i.Title,
		&i.Body,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.DeduplicationKey,
		&i.ReadAt,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, recipient_subject_id, organization_id, title, body,
       related_entity_type, related_entity_id, deduplication_key,
       read_at, revision, created_at
FROM notification_records
WHERE recipient_subject_id = $1 AND tombstoned_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListNotificationsParams struct {
	RecipientSubjectID string `json:"recipient_subject_id"`
	Limit              int32  `json:"limit"`
}

type ListNotificationsRow struct {
	ID                 string             `json:"id"`
	RecipientSubjectID string             `json:"recipient_subject_id"`
	OrganizationID     *string            `json:"organization_id"`
	Title              string             `json:"title"`
	Body               string             `json:"body"`
	RelatedEntityType  *string            `json:"related_entity_type"`
	RelatedEntityID    *string            `json:"related_entity_id"`
	DeduplicationKey   string             `json:"deduplication_key"`
	ReadAt             pgtype.Timestamptz `json:"read_at"`
	Revision           int64              `json:"revision"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.RecipientSubjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipientSubjectID,
			&i.OrganizationID,
			&i.Title,
			&i.Body,
			&i.RelatedEntityType,
			&i.RelatedEntityID,
			&i.DeduplicationKey,
			&i.ReadAt,
			&i.Revision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notification_records
SET read_at = $3,
    revision = revision + 1
WHERE id = $1
  AND recipient_subject_id = $2
  AND revision = $4
  AND read_at IS NULL
  AND tombstoned_at IS NULL
RETURNING id, recipient_subject_id, organization_id, title, body,
          related_entity_type, related_entity_id, deduplication_key,
          read_at, revision, created_at
`

type MarkNotificationReadParams struct {
	ID                 string             `json:"id"`
	RecipientSubjectID string             `json:"recipient_subject_id"`
	ReadAt             pgtype.Timestamptz `json:"read_at"`
	Revision           int64              `json:"revision"`
}

type MarkNotificationReadRow struct {
	ID                 string             `json:"id"`
	RecipientSubjectID string             `json:"recipient_subject_id"`
	OrganizationID     *string            `json:"organization_id"`
	Title              string             `json:"title"`
	Body               string             `json:"body"`
	RelatedEntityType  *string            `json:"related_entity_type"`
	RelatedEntityID    *string            `json:"related_entity_id"`
	DeduplicationKey   string             `json:"deduplication_key"`
	ReadAt             pgtype.Timestamptz `json:"read_at"`
	Revision           int64              `json:"revision"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (MarkNotificationReadRow, error) {
	row := q.db.QueryRow(ctx, markNotificationRead,
		arg.ID,
		arg.RecipientSubjectID,
		arg.ReadAt,
		arg.Revision,
	)
	var i MarkNotificationReadRow
	err := row.Scan(
		&i.ID,
		&i.RecipientSubjectID,
		&i.OrganizationID,
		&i.Title,
		&i.Body,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.DeduplicationKey,
		&i.ReadAt,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const updateNotificationDeliveryJob = `-- name: UpdateNotificationDeliveryJob :one
UPDATE notification_delivery_jobs
SET status = $2,
    attempt_count = $3,
    last_error = $4,
    updated_at = $5
WHERE id = $1
RETURNING id, notification_id, recipient_subject_id, channel, status,
          idempotency_key, outbox_message_id, attempt_count, last_error,
          created_at, updated_at
`

type UpdateNotificationDeliveryJobParams struct {
	ID           string             `json:"id"`
	Status       string             `json:"status"`
	AttemptCount int32              `json:"attempt_count"`
	LastError    *string            `json:"last_error"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateNotificationDeliveryJob(ctx context.Context, arg UpdateNotificationDeliveryJobParams) (NotificationDeliveryJob, error) {
	row := q.db.QueryRow(ctx, updateNotificationDeliveryJob,
		arg.ID,
		arg.Status,
		arg.AttemptCount,
		arg.LastError,
		arg.UpdatedAt,
	)
	var i NotificationDeliveryJob
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.RecipientSubjectID,
		&i.Channel,
		&i.Status,
		&i.IdempotencyKey,
		&i.OutboxMessageID,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
