// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (CreateNotificationRow, error)
	CreateNotificationDeliveryJob(ctx context.Context, arg CreateNotificationDeliveryJobParams) (NotificationDeliveryJob, error)
	CreateReminderDispatch(ctx context.Context, arg CreateReminderDispatchParams) (ReminderDispatch, error)
	GetNotification(ctx context.Context, arg GetNotificationParams) (GetNotificationRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (MarkNotificationReadRow, error)
	UpdateNotificationDeliveryJob(ctx context.Context, arg UpdateNotificationDeliveryJobParams) (NotificationDeliveryJob, error)
}

var _ Querier = (*Queries)(nil)
