// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ReportApprovalState struct {
	ReportVersionID string             `json:"report_version_id"`
	Status          string             `json:"status"`
	Revision        int64              `json:"revision"`
	IssuedAt        pgtype.Timestamptz `json:"issued_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ReportVersion struct {
	ID           string             `json:"id"`
	ReportID     string             `json:"report_id"`
	InspectionID string             `json:"inspection_id"`
	Version      int32              `json:"version"`
	Status       string             `json:"status"`
	Snapshot     []byte             `json:"snapshot"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
