// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetReportApprovalState(ctx context.Context, reportVersionID string) (ReportApprovalState, error)
	GetReportVersion(ctx context.Context, id string) (ReportVersion, error)
}

var _ Querier = (*Queries)(nil)
