// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"
)

const getReportApprovalState = `-- name: GetReportApprovalState :one
SELECT report_version_id, status, revision, issued_at, updated_at
FROM report_approval_states
WHERE report_version_id = $1
FOR UPDATE
`

func (q *Queries) GetReportApprovalState(ctx context.Context, reportVersionID string) (ReportApprovalState, error) {
	row := q.db.QueryRow(ctx, getReportApprovalState, reportVersionID)
	var i ReportApprovalState
	err := row.Scan(
		&i.ReportVersionID,
		&i.Status,
		&i.Revision,
		&i.IssuedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReportVersion = `-- name: GetReportVersion :one
SELECT id, report_id, inspection_id, version, status, snapshot, created_at
FROM report_versions
WHERE id = $1
`

func (q *Queries) GetReportVersion(ctx context.Context, id string) (ReportVersion, error) {
	row := q.db.QueryRow(ctx, getReportVersion, id)
	var i ReportVersion
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.InspectionID,
		&i.Version,
		&i.Status,
		&i.Snapshot,
		&i.CreatedAt,
	)
	return i, err
}
