// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChecklistResponse struct {
	ID                         string             `json:"id"`
	InspectionID               string             `json:"inspection_id"`
	PackageID                  string             `json:"package_id"`
	QuestionID                 string             `json:"question_id"`
	AssignedInspectorSubjectID *string            `json:"assigned_inspector_subject_id"`
	ResponseValue              string             `json:"response_value"`
	CommentToAuditee           *string            `json:"comment_to_auditee"`
	InternalCaaNote            *string            `json:"internal_caa_note"`
	Revision                   int64              `json:"revision"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type InspectionChecklist struct {
	InspectionID string             `json:"inspection_id"`
	Status       string             `json:"status"`
	Revision     int64              `json:"revision"`
	SubmittedAt  pgtype.Timestamptz `json:"submitted_at"`
	ReopenedAt   pgtype.Timestamptz `json:"reopened_at"`
	ReopenReason *string            `json:"reopen_reason"`
}

type InspectionQuestionAssignment struct {
	InspectionID       string `json:"inspection_id"`
	QuestionID         string `json:"question_id"`
	SubjectID          string `json:"subject_id"`
	AssignmentRevision int64  `json:"assignment_revision"`
}
