// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"
)

const getChecklistResponse = `-- name: GetChecklistResponse :one
SELECT id, inspection_id, package_id, question_id, assigned_inspector_subject_id,
       response_value, comment_to_auditee, internal_caa_note, revision, updated_at
FROM checklist_responses
WHERE inspection_id = $1 AND question_id = $2
`

type GetChecklistResponseParams struct {
	InspectionID string `json:"inspection_id"`
	QuestionID   string `json:"question_id"`
}

func (q *Queries) GetChecklistResponse(ctx context.Context, arg GetChecklistResponseParams) (ChecklistResponse, error) {
	row := q.db.QueryRow(ctx, getChecklistResponse, arg.InspectionID, arg.QuestionID)
	var i ChecklistResponse
	err := row.Scan(
		&i.ID,
		&i.InspectionID,
		&i.PackageID,
		&i.QuestionID,
		&i.AssignedInspectorSubjectID,
		&i.ResponseValue,
		&i.CommentToAuditee,
		&i.InternalCaaNote,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const getInspectionChecklist = `-- name: GetInspectionChecklist :one
SELECT inspection_id, status, revision, submitted_at, reopened_at, reopen_reason
FROM inspection_checklists
WHERE inspection_id = $1
`

func (q *Queries) GetInspectionChecklist(ctx context.Context, inspectionID string) (InspectionChecklist, error) {
	row := q.db.QueryRow(ctx, getInspectionChecklist, inspectionID)
	var i InspectionChecklist
	err := row.Scan(
		&i.InspectionID,
		&i.Status,
		&i.Revision,
		&i.SubmittedAt,
		&i.ReopenedAt,
		&i.ReopenReason,
	)
	return i, err
}

const listQuestionAssignments = `-- name: ListQuestionAssignments :many
SELECT inspection_id, question_id, subject_id, assignment_revision
FROM inspection_question_assignments
WHERE inspection_id = $1
ORDER BY question_id, subject_id
`

func (q *Queries) ListQuestionAssignments(ctx context.Context, inspectionID string) ([]InspectionQuestionAssignment, error) {
	rows, err := q.db.Query(ctx, listQuestionAssignments, inspectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InspectionQuestionAssignment
	for rows.Next() {
		var i InspectionQuestionAssignment
		if err := rows.Scan(
			&i.InspectionID,
			&i.QuestionID,
			&i.SubjectID,
			&i.AssignmentRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
