// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetChecklistResponse(ctx context.Context, arg GetChecklistResponseParams) (ChecklistResponse, error)
	GetInspectionChecklist(ctx context.Context, inspectionID string) (InspectionChecklist, error)
	ListQuestionAssignments(ctx context.Context, inspectionID string) ([]InspectionQuestionAssignment, error)
}

var _ Querier = (*Queries)(nil)
