// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DocumentRenderJob struct {
	ID                      string             `json:"id"`
	DocumentID              string             `json:"document_id"`
	OrganizationID          string             `json:"organization_id"`
	RequestedVersion        int32              `json:"requested_version"`
	Status                  string             `json:"status"`
	IdempotencyKey          string             `json:"idempotency_key"`
	InputSnapshot           []byte             `json:"input_snapshot"`
	OutputDocumentVersionID *string            `json:"output_document_version_id"`
	AttemptCount            int32              `json:"attempt_count"`
	LastError               *string            `json:"last_error"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type DocumentVersion struct {
	ID                 string             `json:"id"`
	DocumentID         string             `json:"document_id"`
	OrganizationID     string             `json:"organization_id"`
	Version            int32              `json:"version"`
	Visibility         string             `json:"visibility"`
	Status             string             `json:"status"`
	FileName           string             `json:"file_name"`
	MediaType          string             `json:"media_type"`
	Sha256             string             `json:"sha256"`
	SizeBytes          int64              `json:"size_bytes"`
	ObjectMetadataID   *string            `json:"object_metadata_id"`
	CreatedBySubjectID string             `json:"created_by_subject_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}
