// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateDocumentRecord(ctx context.Context, arg CreateDocumentRecordParams) (CreateDocumentRecordRow, error)
	CreateDocumentRenderJob(ctx context.Context, arg CreateDocumentRenderJobParams) (DocumentRenderJob, error)
	CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error)
	GetDocumentRenderJob(ctx context.Context, id string) (DocumentRenderJob, error)
	GetDocumentVersion(ctx context.Context, id string) (DocumentVersion, error)
	ListDocumentVersions(ctx context.Context, arg ListDocumentVersionsParams) ([]DocumentVersion, error)
	UpdateDocumentRenderJob(ctx context.Context, arg UpdateDocumentRenderJobParams) (DocumentRenderJob, error)
}

var _ Querier = (*Queries)(nil)
