// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocumentRecord = `-- name: CreateDocumentRecord :one
INSERT INTO document_records (
    id, organization_id, kind, title, revision
) VALUES ($1, $2, $3, $4, 1)
RETURNING id, organization_id, kind, title, revision, created_at, updated_at
`

type CreateDocumentRecordParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
	Kind           string `json:"kind"`
	Title          string `json:"title"`
}

type CreateDocumentRecordRow struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	Kind           string             `json:"kind"`
	Title          string             `json:"title"`
	Revision       int64              `json:"revision"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDocumentRecord(ctx context.Context, arg CreateDocumentRecordParams) (CreateDocumentRecordRow, error) {
	row := q.db.QueryRow(ctx, createDocumentRecord,
		arg.ID,
		arg.OrganizationID,
		arg.Kind,
		arg.Title,
	)
	var i CreateDocumentRecordRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.Title,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocumentRenderJob = `-- name: CreateDocumentRenderJob :one
INSERT INTO document_render_jobs (
    id, document_id, organization_id, requested_version, status,
    idempotency_key, input_snapshot
) VALUES ($1, $2, $3, $4, 'PENDING', $5, $6)
RETURNING id, document_id, organization_id, requested_version, status,
          idempotency_key, input_snapshot, output_document_version_id,
          attempt_count, last_error, created_at, updated_at
`

type CreateDocumentRenderJobParams struct {
	ID               string `json:"id"`
	DocumentID       string `json:"document_id"`
	OrganizationID   string `json:"organization_id"`
	RequestedVersion int32  `json:"requested_version"`
	IdempotencyKey   string `json:"idempotency_key"`
	InputSnapshot    []byte `json:"input_snapshot"`
}

func (q *Queries) CreateDocumentRenderJob(ctx context.Context, arg CreateDocumentRenderJobParams) (DocumentRenderJob, error) {
	row := q.db.QueryRow(ctx, createDocumentRenderJob,
		arg.ID,
		arg.DocumentID,
		arg.OrganizationID,
		arg.RequestedVersion,
		arg.IdempotencyKey,
		arg.InputSnapshot,
	)
	var i DocumentRenderJob
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OrganizationID,
		&i.RequestedVersion,
		&i.Status,
		&i.IdempotencyKey,
		&i.InputSnapshot,
		&i.OutputDocumentVersionID,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocumentVersion = `-- name: CreateDocumentVersion :one
INSERT INTO document_versions (
    id, document_id, organization_id, version, visibility, status, file_name,
    media_type, sha256, size_bytes, object_metadata_id, created_by_subject_id,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, document_id, organization_id, version, visibility, status, file_name,
          media_type, sha256, size_bytes, object_metadata_id, created_by_subject_id,
          created_at
`

type CreateDocumentVersionParams struct {
	ID                 string             `json:"id"`
	DocumentID         string             `json:"document_id"`
	OrganizationID     string             `json:"organization_id"`
	Version            int32              `json:"version"`
	Visibility         string             `json:"visibility"`
	Status             string             `json:"status"`
	FileName           string             `json:"file_name"`
	MediaType          string             `json:"media_type"`
	Sha256             string             `json:"sha256"`
	SizeBytes          int64              `json:"size_bytes"`
	ObjectMetadataID   *string            `json:"object_metadata_id"`
	CreatedBySubjectID string             `json:"created_by_subject_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, createDocumentVersion,
		arg.ID,
		arg.DocumentID,
		arg.OrganizationID,
		arg.Version,
		arg.Visibility,
		arg.Status,
		arg.FileName,
		arg.MediaType,
		arg.Sha256,
		arg.SizeBytes,
		arg.ObjectMetadataID,
		arg.CreatedBySubjectID,
		arg.CreatedAt,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OrganizationID,
		&i.Version,
		&i.Visibility,
		&i.Status,
		&i.FileName,
		&i.MediaType,
		&i.Sha256,
		&i.SizeBytes,
		&i.ObjectMetadataID,
		&i.CreatedBySubjectID,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentRenderJob = `-- name: GetDocumentRenderJob :one
SELECT id, document_id, organization_id, requested_version, status,
       idempotency_key, input_snapshot, output_document_version_id,
       attempt_count, last_error, created_at, updated_at
FROM document_render_jobs
WHERE id = $1
`

func (q *Queries) GetDocumentRenderJob(ctx context.Context, id string) (DocumentRenderJob, error) {
	row := q.db.QueryRow(ctx, getDocumentRenderJob, id)
	var i DocumentRenderJob
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OrganizationID,
		&i.RequestedVersion,
		&i.Status,
		&i.IdempotencyKey,
		&i.InputSnapshot,
		&i.OutputDocumentVersionID,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentVersion = `-- name: GetDocumentVersion :one
SELECT id, document_id, organization_id, version, visibility, status, file_name,
       media_type, sha256, size_bytes, object_metadata_id, created_by_subject_id,
       created_at
FROM document_versions
WHERE id = $1
`

func (q *Queries) GetDocumentVersion(ctx context.Context, id string) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getDocumentVersion, id)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OrganizationID,
		&i.Version,
		&i.Visibility,
		&i.Status,
		&i.FileName,
		&i.MediaType,
		&i.Sha256,
		&i.SizeBytes,
		&i.ObjectMetadataID,
		&i.CreatedBySubjectID,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT id, document_id, organization_id, version, visibility, status, file_name,
       media_type, sha256, size_bytes, object_metadata_id, created_by_subject_id,
       created_at
FROM document_versions
WHERE organization_id = $1
  AND visibility = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListDocumentVersionsParams struct {
	OrganizationID string `json:"organization_id"`
	Visibility     string `json:"visibility"`
	ResultLimit    int32  `json:"result_limit"`
}

func (q *Queries) ListDocumentVersions(ctx context.Context, arg ListDocumentVersionsParams) ([]DocumentVersion, error) {
	rows, err := q.db.Query(ctx, listDocumentVersions, arg.OrganizationID, arg.Visibility, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentVersion
	for rows.Next() {
		var i DocumentVersion
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.OrganizationID,
			&i.Version,
			&i.Visibility,
			&i.Status,
			&i.FileName,
			&i.MediaType,
			&i.Sha256,
			&i.SizeBytes,
			&i.ObjectMetadataID,
			&i.CreatedBySubjectID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentRenderJob = `-- name: UpdateDocumentRenderJob :one
UPDATE document_render_jobs
SET status = $2,
    output_document_version_id = $3,
    attempt_count = $4,
    last_error = $5,
    updated_at = $6
WHERE id = $1
RETURNING id, document_id, organization_id, requested_version, status,
          idempotency_key, input_snapshot, output_document_version_id,
          attempt_count, last_error, created_at, updated_at
`

type UpdateDocumentRenderJobParams struct {
	ID                      string             `json:"id"`
	Status                  string             `json:"status"`
	OutputDocumentVersionID *string            `json:"output_document_version_id"`
	AttemptCount            int32              `json:"attempt_count"`
	LastError               *string            `json:"last_error"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateDocumentRenderJob(ctx context.Context, arg UpdateDocumentRenderJobParams) (DocumentRenderJob, error) {
	row := q.db.QueryRow(ctx, updateDocumentRenderJob,
		arg.ID,
		arg.Status,
		arg.OutputDocumentVersionID,
		arg.AttemptCount,
		arg.LastError,
		arg.UpdatedAt,
	)
	var i DocumentRenderJob
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OrganizationID,
		&i.RequestedVersion,
		&i.Status,
		&i.IdempotencyKey,
		&i.InputSnapshot,
		&i.OutputDocumentVersionID,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
