// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityReference struct {
	SubjectID   string             `json:"subject_id"`
	Issuer      string             `json:"issuer"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
