// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UserSetting struct {
	SubjectID               string             `json:"subject_id"`
	NotificationPreferences []byte             `json:"notification_preferences"`
	Locale                  string             `json:"locale"`
	Timezone                string             `json:"timezone"`
	Revision                int64              `json:"revision"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}
