// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIdentityReference = `-- name: GetIdentityReference :one
SELECT subject_id, issuer, display_name, created_at
FROM identity_references
WHERE subject_id = $1
`

func (q *Queries) GetIdentityReference(ctx context.Context, subjectID string) (IdentityReference, error) {
	row := q.db.QueryRow(ctx, getIdentityReference, subjectID)
	var i IdentityReference
	err := row.Scan(
		&i.SubjectID,
		&i.Issuer,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionForAuthentication = `-- name: GetSessionForAuthentication :one
SELECT id, subject_id, organization_id, roles, expires_at, absolute_expires_at, revoked_at,
       csrf_token_hash, provider_session_id
FROM session_references
WHERE session_token_hash = $1
FOR UPDATE
`

type GetSessionForAuthenticationRow struct {
	ID                string             `json:"id"`
	SubjectID         string             `json:"subject_id"`
	OrganizationID    *string            `json:"organization_id"`
	Roles             []string           `json:"roles"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	CsrfTokenHash     *string            `json:"csrf_token_hash"`
	ProviderSessionID *string            `json:"provider_session_id"`
}

func (q *Queries) GetSessionForAuthentication(ctx context.Context, sessionTokenHash *string) (GetSessionForAuthenticationRow, error) {
	row := q.db.QueryRow(ctx, getSessionForAuthentication, sessionTokenHash)
	var i GetSessionForAuthenticationRow
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.OrganizationID,
		&i.Roles,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.CsrfTokenHash,
		&i.ProviderSessionID,
	)
	return i, err
}
