// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetIdentityReference(ctx context.Context, subjectID string) (IdentityReference, error)
	GetSessionForAuthentication(ctx context.Context, sessionTokenHash *string) (GetSessionForAuthenticationRow, error)
}

var _ Querier = (*Queries)(nil)
