// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	ListPlannedInspections(ctx context.Context, arg ListPlannedInspectionsParams) ([]ListPlannedInspectionsRow, error)
}

var _ Querier = (*Queries)(nil)
