// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPlannedInspections = `-- name: ListPlannedInspections :many
SELECT id, organization_id, title, inspection_type, status, due_date, revision
FROM inspections
ORDER BY due_date, id
LIMIT $1 OFFSET $2
`

type ListPlannedInspectionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPlannedInspectionsRow struct {
	ID             string      `json:"id"`
	OrganizationID string      `json:"organization_id"`
	Title          string      `json:"title"`
	InspectionType string      `json:"inspection_type"`
	Status         string      `json:"status"`
	DueDate        pgtype.Date `json:"due_date"`
	Revision       int64       `json:"revision"`
}

func (q *Queries) ListPlannedInspections(ctx context.Context, arg ListPlannedInspectionsParams) ([]ListPlannedInspectionsRow, error) {
	rows, err := q.db.Query(ctx, listPlannedInspections, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlannedInspectionsRow
	for rows.Next() {
		var i ListPlannedInspectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Title,
			&i.InspectionType,
			&i.Status,
			&i.DueDate,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
