// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetSurveillancePlanItemForUpdate(ctx context.Context, id string) (GetSurveillancePlanItemForUpdateRow, error)
	ListPlannedInspections(ctx context.Context, arg ListPlannedInspectionsParams) ([]ListPlannedInspectionsRow, error)
	ListSurveillancePlanItems(ctx context.Context, limit int32) ([]ListSurveillancePlanItemsRow, error)
	UpdateSurveillancePlanDecision(ctx context.Context, arg UpdateSurveillancePlanDecisionParams) (UpdateSurveillancePlanDecisionRow, error)
}

var _ Querier = (*Queries)(nil)
