// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RiskProjectionVersion struct {
	ID             string             `json:"id"`
	ProjectionKind string             `json:"projection_kind"`
	OrganizationID *string            `json:"organization_id"`
	Version        int32              `json:"version"`
	Source         string             `json:"source"`
	Snapshot       []byte             `json:"snapshot"`
	AdvisoryOnly   bool               `json:"advisory_only"`
	CalculatedAt   pgtype.Timestamptz `json:"calculated_at"`
}
