// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateRiskProjectionVersion(ctx context.Context, arg CreateRiskProjectionVersionParams) (RiskProjectionVersion, error)
	GetRiskProjectionVersion(ctx context.Context, id string) (RiskProjectionVersion, error)
	ListRiskProjectionVersions(ctx context.Context, arg ListRiskProjectionVersionsParams) ([]RiskProjectionVersion, error)
}

var _ Querier = (*Queries)(nil)
