// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRiskProjectionVersion = `-- name: CreateRiskProjectionVersion :one
INSERT INTO risk_projection_versions (
    id, projection_kind, organization_id, version, source, snapshot,
    advisory_only, calculated_at
) VALUES ($1, $2, $3, $4, $5, $6, true, $7)
RETURNING id, projection_kind, organization_id, version, source, snapshot,
          advisory_only, calculated_at
`

type CreateRiskProjectionVersionParams struct {
	ID             string             `json:"id"`
	ProjectionKind string             `json:"projection_kind"`
	OrganizationID *string            `json:"organization_id"`
	Version        int32              `json:"version"`
	Source         string             `json:"source"`
	Snapshot       []byte             `json:"snapshot"`
	CalculatedAt   pgtype.Timestamptz `json:"calculated_at"`
}

func (q *Queries) CreateRiskProjectionVersion(ctx context.Context, arg CreateRiskProjectionVersionParams) (RiskProjectionVersion, error) {
	row := q.db.QueryRow(ctx, createRiskProjectionVersion,
		arg.ID,
		arg.ProjectionKind,
		arg.OrganizationID,
		arg.Version,
		arg.Source,
		arg.Snapshot,
		arg.CalculatedAt,
	)
	var i RiskProjectionVersion
	err := row.Scan(
		&i.ID,
		&i.ProjectionKind,
		&i.OrganizationID,
		&i.Version,
		&i.Source,
		&i.Snapshot,
		&i.AdvisoryOnly,
		&i.CalculatedAt,
	)
	return i, err
}

const getRiskProjectionVersion = `-- name: GetRiskProjectionVersion :one
SELECT id, projection_kind, organization_id, version, source, snapshot,
       advisory_only, calculated_at
FROM risk_projection_versions
WHERE id = $1
`

func (q *Queries) GetRiskProjectionVersion(ctx context.Context, id string) (RiskProjectionVersion, error) {
	row := q.db.QueryRow(ctx, getRiskProjectionVersion, id)
	var i RiskProjectionVersion
	err := row.Scan(
		&i.ID,
		&i.ProjectionKind,
		&i.OrganizationID,
		&i.Version,
		&i.Source,
		&i.Snapshot,
		&i.AdvisoryOnly,
		&i.CalculatedAt,
	)
	return i, err
}

const listRiskProjectionVersions = `-- name: ListRiskProjectionVersions :many
SELECT id, projection_kind, organization_id, version, source, snapshot,
       advisory_only, calculated_at
FROM risk_projection_versions
WHERE projection_kind = $1
  AND organization_id IS NOT DISTINCT FROM $2::text
ORDER BY version DESC
LIMIT $3
`

type ListRiskProjectionVersionsParams struct {
	ProjectionKind string  `json:"projection_kind"`
	OrganizationID *string `json:"organization_id"`
	ResultLimit    int32   `json:"result_limit"`
}

func (q *Queries) ListRiskProjectionVersions(ctx context.Context, arg ListRiskProjectionVersionsParams) ([]RiskProjectionVersion, error) {
	rows, err := q.db.Query(ctx, listRiskProjectionVersions, arg.ProjectionKind, arg.OrganizationID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RiskProjectionVersion
	for rows.Next() {
		var i RiskProjectionVersion
		if err := rows.Scan(
			&i.ID,
			&i.ProjectionKind,
			&i.OrganizationID,
			&i.Version,
			&i.Source,
			&i.Snapshot,
			&i.AdvisoryOnly,
			&i.CalculatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
