// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetChecklistTemplateVersion(ctx context.Context, id string) (GetChecklistTemplateVersionRow, error)
	ListChecklistTemplateVersions(ctx context.Context, limit int32) ([]ListChecklistTemplateVersionsRow, error)
	ListReminderRules(ctx context.Context, limit int32) ([]ListReminderRulesRow, error)
}

var _ Querier = (*Queries)(nil)
