// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChecklistTemplateVersion = `-- name: GetChecklistTemplateVersion :one
SELECT id, template_id, title, version, published_at, snapshot,
       jsonb_array_length(snapshot->'questions')::bigint AS question_count
FROM checklist_template_versions
WHERE id = $1
`

type GetChecklistTemplateVersionRow struct {
	ID            string             `json:"id"`
	TemplateID    string             `json:"template_id"`
	Title         string             `json:"title"`
	Version       int32              `json:"version"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	Snapshot      []byte             `json:"snapshot"`
	QuestionCount int64              `json:"question_count"`
}

func (q *Queries) GetChecklistTemplateVersion(ctx context.Context, id string) (GetChecklistTemplateVersionRow, error) {
	row := q.db.QueryRow(ctx, getChecklistTemplateVersion, id)
	var i GetChecklistTemplateVersionRow
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Title,
		&i.Version,
		&i.PublishedAt,
		&i.Snapshot,
		&i.QuestionCount,
	)
	return i, err
}

const listChecklistTemplateVersions = `-- name: ListChecklistTemplateVersions :many
SELECT id, template_id, title, version, published_at,
       jsonb_array_length(snapshot->'questions')::bigint AS question_count
FROM checklist_template_versions
ORDER BY template_id, version DESC
LIMIT $1
`

type ListChecklistTemplateVersionsRow struct {
	ID            string             `json:"id"`
	TemplateID    string             `json:"template_id"`
	Title         string             `json:"title"`
	Version       int32              `json:"version"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	QuestionCount int64              `json:"question_count"`
}

func (q *Queries) ListChecklistTemplateVersions(ctx context.Context, limit int32) ([]ListChecklistTemplateVersionsRow, error) {
	rows, err := q.db.Query(ctx, listChecklistTemplateVersions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChecklistTemplateVersionsRow
	for rows.Next() {
		var i ListChecklistTemplateVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Title,
			&i.Version,
			&i.PublishedAt,
			&i.QuestionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReminderRules = `-- name: ListReminderRules :many
SELECT id, label, offset_days, channel, status, revision
FROM reminder_rules
ORDER BY offset_days DESC, id
LIMIT $1
`

type ListReminderRulesRow struct {
	ID         string `json:"id"`
	Label      string `json:"label"`
	OffsetDays int32  `json:"offset_days"`
	Channel    string `json:"channel"`
	Status     string `json:"status"`
	Revision   int64  `json:"revision"`
}

func (q *Queries) ListReminderRules(ctx context.Context, limit int32) ([]ListReminderRulesRow, error) {
	rows, err := q.db.Query(ctx, listReminderRules, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReminderRulesRow
	for rows.Next() {
		var i ListReminderRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.OffsetDays,
			&i.Channel,
			&i.Status,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
