// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Finding struct {
	ID                 string             `json:"id"`
	Reference          string             `json:"reference"`
	PotentialFindingID *string            `json:"potential_finding_id"`
	InspectionID       string             `json:"inspection_id"`
	OrganizationID     string             `json:"organization_id"`
	Severity           string             `json:"severity"`
	Status             string             `json:"status"`
	OwnerSubjectID     *string            `json:"owner_subject_id"`
	NextAction         string             `json:"next_action"`
	DueDate            pgtype.Date        `json:"due_date"`
	ClosureBasis       *string            `json:"closure_basis"`
	ClosureReason      *string            `json:"closure_reason"`
	Revision           int64              `json:"revision"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
