// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetFinding(ctx context.Context, id string) (Finding, error)
	GetFindingForUpdate(ctx context.Context, id string) (Finding, error)
	ListFindings(ctx context.Context) ([]Finding, error)
	ListFindingsByOrganization(ctx context.Context, organizationID string) ([]Finding, error)
}

var _ Querier = (*Queries)(nil)
