// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"
)

const getFinding = `-- name: GetFinding :one
SELECT id, reference, potential_finding_id, inspection_id, organization_id, severity, status,
       owner_subject_id, next_action, due_date, closure_basis, closure_reason, revision, created_at, updated_at
FROM findings
WHERE id = $1
`

func (q *Queries) GetFinding(ctx context.Context, id string) (Finding, error) {
	row := q.db.QueryRow(ctx, getFinding, id)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.PotentialFindingID,
		&i.InspectionID,
		&i.OrganizationID,
		&i.Severity,
		&i.Status,
		&i.OwnerSubjectID,
		&i.NextAction,
		&i.DueDate,
		&i.ClosureBasis,
		&i.ClosureReason,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFindingForUpdate = `-- name: GetFindingForUpdate :one
SELECT id, reference, potential_finding_id, inspection_id, organization_id, severity, status,
       owner_subject_id, next_action, due_date, closure_basis, closure_reason, revision, created_at, updated_at
FROM findings
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetFindingForUpdate(ctx context.Context, id string) (Finding, error) {
	row := q.db.QueryRow(ctx, getFindingForUpdate, id)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.PotentialFindingID,
		&i.InspectionID,
		&i.OrganizationID,
		&i.Severity,
		&i.Status,
		&i.OwnerSubjectID,
		&i.NextAction,
		&i.DueDate,
		&i.ClosureBasis,
		&i.ClosureReason,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFindings = `-- name: ListFindings :many
SELECT id, reference, potential_finding_id, inspection_id, organization_id, severity, status,
       owner_subject_id, next_action, due_date, closure_basis, closure_reason, revision, created_at, updated_at
FROM findings
ORDER BY reference
`

func (q *Queries) ListFindings(ctx context.Context) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.PotentialFindingID,
			&i.InspectionID,
			&i.OrganizationID,
			&i.Severity,
			&i.Status,
			&i.OwnerSubjectID,
			&i.NextAction,
			&i.DueDate,
			&i.ClosureBasis,
			&i.ClosureReason,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByOrganization = `-- name: ListFindingsByOrganization :many
SELECT id, reference, potential_finding_id, inspection_id, organization_id, severity, status,
       owner_subject_id, next_action, due_date, closure_basis, closure_reason, revision, created_at, updated_at
FROM findings
WHERE organization_id = $1
ORDER BY reference
`

func (q *Queries) ListFindingsByOrganization(ctx context.Context, organizationID string) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.PotentialFindingID,
			&i.InspectionID,
			&i.OrganizationID,
			&i.Severity,
			&i.Status,
			&i.OwnerSubjectID,
			&i.NextAction,
			&i.DueDate,
			&i.ClosureBasis,
			&i.ClosureReason,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
