version: ENC[AES256_GCM,data:Sw==,iv:PLIWjEWx2W0i1Rz62LvIYUUaG8IkdRyUZ48rL7NPufk=,tag:+GDEF+KMdEVZhx25JL9PRQ==,type:int]
environment: ENC[AES256_GCM,data:kcejFGMOnE5cjR+VfCTJnPhIOlHp,iv:7mZUyKKSV8T3UNeCCQNGrwwwe+tE4YsYoeVecXGf4Xw=,tag:+8fkjeXymsEWUSc0KYsGJg==,type:str]
http:
    listenAddress: ENC[AES256_GCM,data:ua5KMWTx1TfWBT7/,iv:F7SVtzoNvy64vuSBAdb307ubVHTFSYYzcvB/c3KVtt0=,tag:Uei2bpKOTPf8ezwvKsMv/w==,type:str]
    publicOrigin: ENC[AES256_GCM,data:oS2HFMG0kQ+NoP7qjKFBz7fD7wZR3g==,iv:4kvPjPhb1WwntmeZ+MHcpASn4sS9949TUEUosm0wNok=,tag:w2hsjkMobJf4K0rH0Ayxdg==,type:str]
database:
    host: ENC[AES256_GCM,data:H4WOy5+dYeY=,iv:oMmsTcu4BCNbGExmZgkd678m+Xw0CT8KdahbYUHDATM=,tag:Z8i6YRQSmlKQoT+AmXP06A==,type:str]
    port: ENC[AES256_GCM,data:saa8yg==,iv:WVNdoHZ7ze1o5DHjc7P8bwEXo28jw7akE49wswxKsXQ=,tag:M69as9edAYnJf1rkvvzbSQ==,type:int]
    name: ENC[AES256_GCM,data:JSb3mRDv0WtGKKWNyYM=,iv:+Mfa73FagU0FZBPBKl4UgrDTW0x5xtn3Jth5bXrDevw=,tag:P+nJSN8PGH0B1mndeM+fsA==,type:str]
    user: ENC[AES256_GCM,data:fh09AzoH/7CVlMnwN74=,iv:qYkoj3eMzItn4ml99iJ8s0L+FKGG4kn8HQuieKc7qv0=,tag:7Lm2+kQr2CLi475OA7/ydQ==,type:str]
    passwordFile: ENC[AES256_GCM,data:zYoWLfE89hPHoGlJpnaf1wOa6s25Pq7ugcme1Dn/8T1pfQ==,iv:D38+B0i3ddeB3I8iGuQtvQxIlOMoXgDKljd+hgt2HfI=,tag:Y0tUQ/IUz67c96MKUxuICg==,type:str]
identity:
    issuer: ENC[AES256_GCM,data:s6gcIVDMHs03eTARwevlMSo5tx7Ec5P14kNs729avP48hUNrcZbIhPLqS4FZIQTbrY5vzig=,iv:PCLmooH1q++sDwI1Xu4wIVQk+hdW3YxmbE+mqDJuSQE=,tag:YXnW51hsz0x8MT5eU7zdUg==,type:str]
    internalIssuer: ENC[AES256_GCM,data:P2TxBoHk83I/oUs2hNZHBQqTWvifbO8cNHYK5ffmTVQPMvx1nlsIacBDLLc/EkDTdJQA,iv:8UStTJePIuzW58PcUsi42lse6C/vYimnQjN4U7s8xP8=,tag:JyEkT0fHh51VJQ/sz0paTg==,type:str]
    clientId: ENC[AES256_GCM,data:a2Q/xNfYdmpoDnr83B7eNCMs,iv:H8qC8LldufWBhHXnsrowEPIKDq0iugMIikJ0ourMSJ8=,tag:xS8I5M6JN/40U/uG+zzSfQ==,type:str]
    clientSecretFile: ENC[AES256_GCM,data:HNeiTxXL43iUH9X+tllp9f6q3YZomDBd22skvs99Ww==,iv:X6C5prU2OtrYUfTRnTTwu4eT2JfaEMLTKoaSGKWZywA=,tag:SiHU6h8yzezazrCfQR22qg==,type:str]
    bootstrapAdminPasswordFile: ENC[AES256_GCM,data:FFAgnvpiheDtkHAobZGFE8BEUox4zz8CXVss5KhTqpbjAPFibwPeeA5tI7d49w==,iv:gLoV6IWD8qj2Z/3PEoLVHsyqIuMPJplgNcjkgCF3g2k=,tag:jwoNVrjKVJ9NcV+y5ntjKQ==,type:str]
session:
    encryptionKeyFile: ENC[AES256_GCM,data:WmS/XJJFatUziFVAfk1THoRcnz6Xln9GNAmoBIUTRIoplUk=,iv:XEgtXpUG5LC788G2CCRLMLdljRz7PFfFEDMNXHd+F1U=,tag:4aVFM1kxpkqm6lxwCOTfvA==,type:str]
objectStorage:
    endpoint: ENC[AES256_GCM,data:YvT/gusAWye8+Apk4/iWJOE=,iv:2kGFhl+iO/y75iPvn0O1rQubyS9+vBpLcOd7xePYEHE=,tag:mVYvac1+Cs3wjptclWYNDQ==,type:str]
    accessKeyFile: ENC[AES256_GCM,data:aVOM7qXY9RMhxaewFO5RCj+e6WY+SAvzBpHrRg==,iv:daZqDn5jOpI/5dpexnoFCZeERitAKF4bofsIIPIu98M=,tag:YDl2T4Ityt6ayvzADglg5g==,type:str]
    secretKeyFile: ENC[AES256_GCM,data:KvME5YxeIpLQw+TjHsUiaEdjZTfXh+E0PFAfDAnzAsw=,iv:IjryqZpQg2zWFZX4Y4bkdX+UDHMpwzuVv3CY+enEJh4=,tag:kbZG1A55rGasl8403IpJnw==,type:str]
scanner:
    address: ENC[AES256_GCM,data:X8H6C4w6LMs3Ksg=,iv:tgPnI7FuEmq1dzXvWDz9LrtMgu2u0i8Hc4br9xcUfOw=,tag:wCgqtJwxjisx/H33zyYXFg==,type:str]
smtp:
    address: ENC[AES256_GCM,data:EkhfSJHf4Hk21FJI,iv:0rFS1+Jg66JaMWPv7k2PS7NiHtPDO+WX6hZQu53Fcmw=,tag:X9tNIV2Lx8CYo/cwm4ABzQ==,type:str]
    username: ENC[AES256_GCM,data:4UmkcubC1tsM+ErNimc=,iv:mxMRbrI/Pb2UQpYMrA/Y5vcH3XC87zR0jmHhHP4r8TE=,tag:VGjgrTW6hyDcJTAsTMTfNQ==,type:str]
    passwordFile: ENC[AES256_GCM,data:Z+DRuxhmFhvo3AAJj9tQyr8uzCjTTfFjazM=,iv:9P34HrptyvA/6Y9OZQEn5ZAAN9vaZOWB0E5Gs9a4Yuk=,tag:TcGljhdL3cGvurTCLWiV5w==,type:str]
renderer:
    endpoint: ENC[AES256_GCM,data:r6wUXYMtSeBR3VrkpfjPiqYAufZE,iv:5ghXzykPA04Sy2PyC5wETsVohN1s/CsXrQroZKTaoVQ=,tag:zgE88Kg8tVGWg5Afjc3YrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWnM5YzNIZmFNRTA1ZFdS
            Nm1BUjgyMDJyVVVndXErQU0xbGtPV1B3elJBCkNkcGt4QTZQNnc0L3pQeVpCeWVv
            RXl0anNzV1NyL2V2ZXVlMm1QbW0xRGsKLS0tIEN2MThVcitCTEVsK1Bsd2k3dDVU
            c3lKc2JqMWxWNmlOWGFJY2dsc1BQNEEK7sjNdv7YmROVbP4JP9mNxNaVK52Dzd8G
            0a4zZ8mhkhm6yqew1Xtd5voL4kKSSFUFwDo50KY6ov22XIX6VnlFpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w0vrwyn3fnqw3mxcm9ahusdfvzk2jg7akeslh5ttdxkdxw0stanspr3mpy
    lastmodified: "2026-07-24T10:42:22Z"
    mac: ENC[AES256_GCM,data:gxqq7Br6MAmRDXWACAuZk5i3mS8N3iLwteV5bseuN0bjzUJHZXgwHDeuKJhXMNIfyn12t8ngA/NNYkyDGkH8yvYp9H8pWa0PR7BbkXnnmQ/whEli0yGklf7Cy1ZvZDDBV1f++90OTiYVImrBd4hPbhN2WGQetXdCTMBgZIWfIm4=,iv:ycVzSCvO8tpVgBJNJi+fzML1CZNAb79+1+26o3H3u+E=,tag:2t7s1Ptavc43U9s8gU7hAw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
