// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EvidenceVersion struct {
	ID                   string             `json:"id"`
	EvidenceID           string             `json:"evidence_id"`
	FindingID            string             `json:"finding_id"`
	OrganizationID       string             `json:"organization_id"`
	Version              int32              `json:"version"`
	ObjectMetadataID     *string            `json:"object_metadata_id"`
	Filename             string             `json:"filename"`
	MediaType            string             `json:"media_type"`
	Sha256               string             `json:"sha256"`
	SizeBytes            int64              `json:"size_bytes"`
	Status               string             `json:"status"`
	SubmittedBySubjectID string             `json:"submitted_by_subject_id"`
	SubmittedAt          pgtype.Timestamptz `json:"submitted_at"`
	Revision             int64              `json:"revision"`
}
