// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetEvidenceVersion(ctx context.Context, id string) (EvidenceVersion, error)
	ListEvidenceVersions(ctx context.Context, evidenceID string) ([]EvidenceVersion, error)
}

var _ Querier = (*Queries)(nil)
