// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"
)

const getEvidenceVersion = `-- name: GetEvidenceVersion :one
SELECT id, evidence_id, finding_id, organization_id, version, object_metadata_id, filename,
       media_type, sha256, size_bytes, status, submitted_by_subject_id, submitted_at, revision
FROM evidence_versions
WHERE id = $1
`

func (q *Queries) GetEvidenceVersion(ctx context.Context, id string) (EvidenceVersion, error) {
	row := q.db.QueryRow(ctx, getEvidenceVersion, id)
	var i EvidenceVersion
	err := row.Scan(
		&i.ID,
		&i.EvidenceID,
		&i.FindingID,
		&i.OrganizationID,
		&i.Version,
		&i.ObjectMetadataID,
		&i.Filename,
		&i.MediaType,
		&i.Sha256,
		&i.SizeBytes,
		&i.Status,
		&i.SubmittedBySubjectID,
		&i.SubmittedAt,
		&i.Revision,
	)
	return i, err
}

const listEvidenceVersions = `-- name: ListEvidenceVersions :many
SELECT id, evidence_id, finding_id, organization_id, version, object_metadata_id, filename,
       media_type, sha256, size_bytes, status, submitted_by_subject_id, submitted_at, revision
FROM evidence_versions
WHERE evidence_id = $1
ORDER BY version
`

func (q *Queries) ListEvidenceVersions(ctx context.Context, evidenceID string) ([]EvidenceVersion, error) {
	rows, err := q.db.Query(ctx, listEvidenceVersions, evidenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvidenceVersion
	for rows.Next() {
		var i EvidenceVersion
		if err := rows.Scan(
			&i.ID,
			&i.EvidenceID,
			&i.FindingID,
			&i.OrganizationID,
			&i.Version,
			&i.ObjectMetadataID,
			&i.Filename,
			&i.MediaType,
			&i.Sha256,
			&i.SizeBytes,
			&i.Status,
			&i.SubmittedBySubjectID,
			&i.SubmittedAt,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
