// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CapRevision struct {
	ID                   string             `json:"id"`
	CapID                string             `json:"cap_id"`
	FindingID            string             `json:"finding_id"`
	OrganizationID       string             `json:"organization_id"`
	Revision             int32              `json:"revision"`
	Status               string             `json:"status"`
	RootCause            string             `json:"root_cause"`
	CorrectiveAction     string             `json:"corrective_action"`
	PreventiveAction     string             `json:"preventive_action"`
	TargetCompletionDate pgtype.Date        `json:"target_completion_date"`
	SubmittedBySubjectID string             `json:"submitted_by_subject_id"`
	SubmittedAt          pgtype.Timestamptz `json:"submitted_at"`
	ResponsiblePerson    *string            `json:"responsible_person"`
	CommentToCaa         *string            `json:"comment_to_caa"`
}
