// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetCAPRevision(ctx context.Context, id string) (CapRevision, error)
	GetLatestCAPRevisionForFinding(ctx context.Context, findingID string) (CapRevision, error)
}

var _ Querier = (*Queries)(nil)
