// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"
)

const getCAPRevision = `-- name: GetCAPRevision :one
SELECT id, cap_id, finding_id, organization_id, revision, status, root_cause, corrective_action,
       preventive_action, target_completion_date, submitted_by_subject_id, submitted_at,
       responsible_person, comment_to_caa
FROM cap_revisions
WHERE id = $1
`

func (q *Queries) GetCAPRevision(ctx context.Context, id string) (CapRevision, error) {
	row := q.db.QueryRow(ctx, getCAPRevision, id)
	var i CapRevision
	err := row.Scan(
		&i.ID,
		&i.CapID,
		&i.FindingID,
		&i.OrganizationID,
		&i.Revision,
		&i.Status,
		&i.RootCause,
		&i.CorrectiveAction,
		&i.PreventiveAction,
		&i.TargetCompletionDate,
		&i.SubmittedBySubjectID,
		&i.SubmittedAt,
		&i.ResponsiblePerson,
		&i.CommentToCaa,
	)
	return i, err
}

const getLatestCAPRevisionForFinding = `-- name: GetLatestCAPRevisionForFinding :one
SELECT id, cap_id, finding_id, organization_id, revision, status, root_cause, corrective_action,
       preventive_action, target_completion_date, submitted_by_subject_id, submitted_at,
       responsible_person, comment_to_caa
FROM cap_revisions
WHERE finding_id = $1
ORDER BY revision DESC
LIMIT 1
`

func (q *Queries) GetLatestCAPRevisionForFinding(ctx context.Context, findingID string) (CapRevision, error) {
	row := q.db.QueryRow(ctx, getLatestCAPRevisionForFinding, findingID)
	var i CapRevision
	err := row.Scan(
		&i.ID,
		&i.CapID,
		&i.FindingID,
		&i.OrganizationID,
		&i.Revision,
		&i.Status,
		&i.RootCause,
		&i.CorrectiveAction,
		&i.PreventiveAction,
		&i.TargetCompletionDate,
		&i.SubmittedBySubjectID,
		&i.SubmittedAt,
		&i.ResponsiblePerson,
		&i.CommentToCaa,
	)
	return i, err
}
