// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CommunicationAttachment struct {
	ID               string             `json:"id"`
	MessageID        string             `json:"message_id"`
	OrganizationID   *string            `json:"organization_id"`
	ObjectMetadataID string             `json:"object_metadata_id"`
	FileName         string             `json:"file_name"`
	MediaType        string             `json:"media_type"`
	SizeBytes        int64              `json:"size_bytes"`
	Sha256           string             `json:"sha256"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type CommunicationMessage struct {
	ID              string             `json:"id"`
	ThreadID        string             `json:"thread_id"`
	OrganizationID  *string            `json:"organization_id"`
	Visibility      string             `json:"visibility"`
	SenderSubjectID string             `json:"sender_subject_id"`
	Audience        string             `json:"audience"`
	Direction       string             `json:"direction"`
	Subject         string             `json:"subject"`
	Body            string             `json:"body"`
	IdempotencyKey  string             `json:"idempotency_key"`
	Revision        int64              `json:"revision"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
