// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateCommunicationAttachment(ctx context.Context, arg CreateCommunicationAttachmentParams) (CommunicationAttachment, error)
	CreateCommunicationMessage(ctx context.Context, arg CreateCommunicationMessageParams) (CommunicationMessage, error)
	CreateCommunicationThread(ctx context.Context, arg CreateCommunicationThreadParams) (CreateCommunicationThreadRow, error)
	GetCommunicationMessage(ctx context.Context, id string) (CommunicationMessage, error)
	ListCommunicationAttachments(ctx context.Context, messageID string) ([]CommunicationAttachment, error)
	ListCommunicationMessages(ctx context.Context, arg ListCommunicationMessagesParams) ([]CommunicationMessage, error)
	ListInternalCommunicationMessages(ctx context.Context, limit int32) ([]CommunicationMessage, error)
}

var _ Querier = (*Queries)(nil)
