// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCommunicationAttachment = `-- name: CreateCommunicationAttachment :one
INSERT INTO communication_attachments (
    id, message_id, organization_id, object_metadata_id, file_name,
    media_type, size_bytes, sha256, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, message_id, organization_id, object_metadata_id, file_name,
          media_type, size_bytes, sha256, created_at
`

type CreateCommunicationAttachmentParams struct {
	ID               string             `json:"id"`
	MessageID        string             `json:"message_id"`
	OrganizationID   *string            `json:"organization_id"`
	ObjectMetadataID string             `json:"object_metadata_id"`
	FileName         string             `json:"file_name"`
	MediaType        string             `json:"media_type"`
	SizeBytes        int64              `json:"size_bytes"`
	Sha256           string             `json:"sha256"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateCommunicationAttachment(ctx context.Context, arg CreateCommunicationAttachmentParams) (CommunicationAttachment, error) {
	row := q.db.QueryRow(ctx, createCommunicationAttachment,
		arg.ID,
		arg.MessageID,
		arg.OrganizationID,
		arg.ObjectMetadataID,
		arg.FileName,
		arg.MediaType,
		arg.SizeBytes,
		arg.Sha256,
		arg.CreatedAt,
	)
	var i CommunicationAttachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.OrganizationID,
		&i.ObjectMetadataID,
		&i.FileName,
		&i.MediaType,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const createCommunicationMessage = `-- name: CreateCommunicationMessage :one
INSERT INTO communication_messages (
    id, thread_id, organization_id, visibility, sender_subject_id, audience,
    direction, subject, body, idempotency_key, revision, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 1, $11)
RETURNING id, thread_id, organization_id, visibility, sender_subject_id, audience,
          direction, subject, body, idempotency_key, revision, created_at
`

type CreateCommunicationMessageParams struct {
	ID              string             `json:"id"`
	ThreadID        string             `json:"thread_id"`
	OrganizationID  *string            `json:"organization_id"`
	Visibility      string             `json:"visibility"`
	SenderSubjectID string             `json:"sender_subject_id"`
	Audience        string             `json:"audience"`
	Direction       string             `json:"direction"`
	Subject         string             `json:"subject"`
	Body            string             `json:"body"`
	IdempotencyKey  string             `json:"idempotency_key"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateCommunicationMessage(ctx context.Context, arg CreateCommunicationMessageParams) (CommunicationMessage, error) {
	row := q.db.QueryRow(ctx, createCommunicationMessage,
		arg.ID,
		arg.ThreadID,
		arg.OrganizationID,
		arg.Visibility,
		arg.SenderSubjectID,
		arg.Audience,
		arg.Direction,
		arg.Subject,
		arg.Body,
		arg.IdempotencyKey,
		arg.CreatedAt,
	)
	var i CommunicationMessage
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.OrganizationID,
		&i.Visibility,
		&i.SenderSubjectID,
		&i.Audience,
		&i.Direction,
		&i.Subject,
		&i.Body,
		&i.IdempotencyKey,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const createCommunicationThread = `-- name: CreateCommunicationThread :one
INSERT INTO communication_threads (
    id, organization_id, visibility, subject, revision
) VALUES ($1, $2, $3, $4, 1)
RETURNING id, organization_id, visibility, subject, revision, created_at, updated_at
`

type CreateCommunicationThreadParams struct {
	ID             string  `json:"id"`
	OrganizationID *string `json:"organization_id"`
	Visibility     string  `json:"visibility"`
	Subject        string  `json:"subject"`
}

type CreateCommunicationThreadRow struct {
	ID             string             `json:"id"`
	OrganizationID *string            `json:"organization_id"`
	Visibility     string             `json:"visibility"`
	Subject        string             `json:"subject"`
	Revision       int64              `json:"revision"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCommunicationThread(ctx context.Context, arg CreateCommunicationThreadParams) (CreateCommunicationThreadRow, error) {
	row := q.db.QueryRow(ctx, createCommunicationThread,
		arg.ID,
		arg.OrganizationID,
		arg.Visibility,
		arg.Subject,
	)
	var i CreateCommunicationThreadRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Visibility,
		&i.Subject,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommunicationMessage = `-- name: GetCommunicationMessage :one
SELECT id, thread_id, organization_id, visibility, sender_subject_id, audience,
       direction, subject, body, idempotency_key, revision, created_at
FROM communication_messages
WHERE id = $1
`

func (q *Queries) GetCommunicationMessage(ctx context.Context, id string) (CommunicationMessage, error) {
	row := q.db.QueryRow(ctx, getCommunicationMessage, id)
	var i CommunicationMessage
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.OrganizationID,
		&i.Visibility,
		&i.SenderSubjectID,
		&i.Audience,
		&i.Direction,
		&i.Subject,
		&i.Body,
		&i.IdempotencyKey,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const listCommunicationAttachments = `-- name: ListCommunicationAttachments :many
SELECT id, message_id, organization_id, object_metadata_id, file_name,
       media_type, size_bytes, sha256, created_at
FROM communication_attachments
WHERE message_id = $1
ORDER BY id
`

func (q *Queries) ListCommunicationAttachments(ctx context.Context, messageID string) ([]CommunicationAttachment, error) {
	rows, err := q.db.Query(ctx, listCommunicationAttachments, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunicationAttachment
	for rows.Next() {
		var i CommunicationAttachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.OrganizationID,
			&i.ObjectMetadataID,
			&i.FileName,
			&i.MediaType,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunicationMessages = `-- name: ListCommunicationMessages :many
SELECT id, thread_id, organization_id, visibility, sender_subject_id, audience,
       direction, subject, body, idempotency_key, revision, created_at
FROM communication_messages
WHERE organization_id = $1
  AND visibility = $2
  AND (
      $3::timestamptz IS NULL
      OR (created_at, id) < (
          $3::timestamptz,
          $4::text
      )
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListCommunicationMessagesParams struct {
	OrganizationID  *string            `json:"organization_id"`
	Visibility      string             `json:"visibility"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        string             `json:"before_id"`
	ResultLimit     int32              `json:"result_limit"`
}

func (q *Queries) ListCommunicationMessages(ctx context.Context, arg ListCommunicationMessagesParams) ([]CommunicationMessage, error) {
	rows, err := q.db.Query(ctx, listCommunicationMessages,
		arg.OrganizationID,
		arg.Visibility,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunicationMessage
	for rows.Next() {
		var i CommunicationMessage
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.OrganizationID,
			&i.Visibility,
			&i.SenderSubjectID,
			&i.Audience,
			&i.Direction,
			&i.Subject,
			&i.Body,
			&i.IdempotencyKey,
			&i.Revision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInternalCommunicationMessages = `-- name: ListInternalCommunicationMessages :many
SELECT id, thread_id, organization_id, visibility, sender_subject_id, audience,
       direction, subject, body, idempotency_key, revision, created_at
FROM communication_messages
WHERE visibility = 'INTERNAL_CAA'
ORDER BY created_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListInternalCommunicationMessages(ctx context.Context, limit int32) ([]CommunicationMessage, error) {
	rows, err := q.db.Query(ctx, listInternalCommunicationMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunicationMessage
	for rows.Next() {
		var i CommunicationMessage
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.OrganizationID,
			&i.Visibility,
			&i.SenderSubjectID,
			&i.Audience,
			&i.Direction,
			&i.Subject,
			&i.Body,
			&i.IdempotencyKey,
			&i.Revision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
