// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	SequenceID     int64              `json:"sequence_id"`
	EventID        string             `json:"event_id"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	ActorSubjectID *string            `json:"actor_subject_id"`
	ActorRole      *string            `json:"actor_role"`
	OrganizationID *string            `json:"organization_id"`
	Action         string             `json:"action"`
	EntityType     string             `json:"entity_type"`
	EntityID       string             `json:"entity_id"`
	RequestID      *string            `json:"request_id"`
	Details        []byte             `json:"details"`
	EntityVersion  *int64             `json:"entity_version"`
	BeforeStatus   *string            `json:"before_status"`
	AfterStatus    *string            `json:"after_status"`
	Reason         *string            `json:"reason"`
	OperationID    *string            `json:"operation_id"`
	CorrelationID  *string            `json:"correlation_id"`
	ClosureBasis   *string            `json:"closure_basis"`
}
