// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListAuditEventsForEntity(ctx context.Context, arg ListAuditEventsForEntityParams) ([]AuditEvent, error)
}

var _ Querier = (*Queries)(nil)
