// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	AddAuditQuestionAssignment(ctx context.Context, arg AddAuditQuestionAssignmentParams) (AddAuditQuestionAssignmentRow, error)
	AddAuditTeamMember(ctx context.Context, arg AddAuditTeamMemberParams) (AddAuditTeamMemberRow, error)
	CreateAuditAssignment(ctx context.Context, arg CreateAuditAssignmentParams) (CreateAuditAssignmentRow, error)
	GetAuditAssignment(ctx context.Context, id string) (GetAuditAssignmentRow, error)
	ListAuditAssignments(ctx context.Context, arg ListAuditAssignmentsParams) ([]ListAuditAssignmentsRow, error)
	ListAuditQuestionAssignments(ctx context.Context, assignmentID string) ([]ListAuditQuestionAssignmentsRow, error)
	ListAuditTeamMembers(ctx context.Context, assignmentID string) ([]ListAuditTeamMembersRow, error)
	UpdateAuditAssignment(ctx context.Context, arg UpdateAuditAssignmentParams) (UpdateAuditAssignmentRow, error)
}

var _ Querier = (*Queries)(nil)
