// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAuditQuestionAssignment = `-- name: AddAuditQuestionAssignment :one
INSERT INTO audit_question_assignments (
    assignment_id, question_id, subject_id, revision
) VALUES ($1, $2, $3, 1)
RETURNING assignment_id, question_id, subject_id, revision
`

type AddAuditQuestionAssignmentParams struct {
	AssignmentID string `json:"assignment_id"`
	QuestionID   string `json:"question_id"`
	SubjectID    string `json:"subject_id"`
}

type AddAuditQuestionAssignmentRow struct {
	AssignmentID string `json:"assignment_id"`
	QuestionID   string `json:"question_id"`
	SubjectID    string `json:"subject_id"`
	Revision     int64  `json:"revision"`
}

func (q *Queries) AddAuditQuestionAssignment(ctx context.Context, arg AddAuditQuestionAssignmentParams) (AddAuditQuestionAssignmentRow, error) {
	row := q.db.QueryRow(ctx, addAuditQuestionAssignment, arg.AssignmentID, arg.QuestionID, arg.SubjectID)
	var i AddAuditQuestionAssignmentRow
	err := row.Scan(
		&i.AssignmentID,
		&i.QuestionID,
		&i.SubjectID,
		&i.Revision,
	)
	return i, err
}

const addAuditTeamMember = `-- name: AddAuditTeamMember :one
INSERT INTO audit_team_members (
    assignment_id, subject_id, member_role, revision
) VALUES ($1, $2, $3, 1)
RETURNING assignment_id, subject_id, member_role, revision
`

type AddAuditTeamMemberParams struct {
	AssignmentID string `json:"assignment_id"`
	SubjectID    string `json:"subject_id"`
	MemberRole   string `json:"member_role"`
}

type AddAuditTeamMemberRow struct {
	AssignmentID string `json:"assignment_id"`
	SubjectID    string `json:"subject_id"`
	MemberRole   string `json:"member_role"`
	Revision     int64  `json:"revision"`
}

func (q *Queries) AddAuditTeamMember(ctx context.Context, arg AddAuditTeamMemberParams) (AddAuditTeamMemberRow, error) {
	row := q.db.QueryRow(ctx, addAuditTeamMember, arg.AssignmentID, arg.SubjectID, arg.MemberRole)
	var i AddAuditTeamMemberRow
	err := row.Scan(
		&i.AssignmentID,
		&i.SubjectID,
		&i.MemberRole,
		&i.Revision,
	)
	return i, err
}

const createAuditAssignment = `-- name: CreateAuditAssignment :one
INSERT INTO audit_assignments (
    id, inspection_id, organization_id, lead_subject_id, status,
    scheduled_start_date, scheduled_end_date, revision
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 1
)
RETURNING id, inspection_id, organization_id, lead_subject_id, status,
          scheduled_start_date, scheduled_end_date, revision
`

type CreateAuditAssignmentParams struct {
	ID                 string      `json:"id"`
	InspectionID       string      `json:"inspection_id"`
	OrganizationID     string      `json:"organization_id"`
	LeadSubjectID      string      `json:"lead_subject_id"`
	Status             string      `json:"status"`
	ScheduledStartDate pgtype.Date `json:"scheduled_start_date"`
	ScheduledEndDate   pgtype.Date `json:"scheduled_end_date"`
}

type CreateAuditAssignmentRow struct {
	ID                 string      `json:"id"`
	InspectionID       string      `json:"inspection_id"`
	OrganizationID     string      `json:"organization_id"`
	LeadSubjectID      string      `json:"lead_subject_id"`
	Status             string      `json:"status"`
	ScheduledStartDate pgtype.Date `json:"scheduled_start_date"`
	ScheduledEndDate   pgtype.Date `json:"scheduled_end_date"`
	Revision           int64       `json:"revision"`
}

func (q *Queries) CreateAuditAssignment(ctx context.Context, arg CreateAuditAssignmentParams) (CreateAuditAssignmentRow, error) {
	row := q.db.QueryRow(ctx, createAuditAssignment,
		arg.ID,
		arg.InspectionID,
		arg.OrganizationID,
		arg.LeadSubjectID,
		arg.Status,
		arg.ScheduledStartDate,
		arg.ScheduledEndDate,
	)
	var i CreateAuditAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.InspectionID,
		&i.OrganizationID,
		&i.LeadSubjectID,
		&i.Status,
		&i.ScheduledStartDate,
		&i.ScheduledEndDate,
		&i.Revision,
	)
	return i, err
}

const getAuditAssignment = `-- name: GetAuditAssignment :one
SELECT id, inspection_id, organization_id, lead_subject_id, status,
       scheduled_start_date, scheduled_end_date, revision
FROM audit_assignments
WHERE id = $1 AND tombstoned_at IS NULL
`

type GetAuditAssignmentRow struct {
	ID                 string      `json:"id"`
	InspectionID       string      `json:"inspection_id"`
	OrganizationID     string      `json:"organization_id"`
	LeadSubjectID      string      `json:"lead_subject_id"`
	Status             string      `json:"status"`
	ScheduledStartDate pgtype.Date `json:"scheduled_start_date"`
	ScheduledEndDate   pgtype.Date `json:"scheduled_end_date"`
	Revision           int64       `json:"revision"`
}

func (q *Queries) GetAuditAssignment(ctx context.Context, id string) (GetAuditAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getAuditAssignment, id)
	var i GetAuditAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.InspectionID,
		&i.OrganizationID,
		&i.LeadSubjectID,
		&i.Status,
		&i.ScheduledStartDate,
		&i.ScheduledEndDate,
		&i.Revision,
	)
	return i, err
}

const listAuditAssignments = `-- name: ListAuditAssignments :many
SELECT id, inspection_id, organization_id, lead_subject_id, status,
       scheduled_start_date, scheduled_end_date, revision
FROM audit_assignments
WHERE organization_id = $1
  AND ($2::text = '' OR status = $2::text)
  AND tombstoned_at IS NULL
ORDER BY scheduled_start_date, id
LIMIT $3
`

type ListAuditAssignmentsParams struct {
	OrganizationID string `json:"organization_id"`
	StatusFilter   string `json:"status_filter"`
	ResultLimit    int32  `json:"result_limit"`
}

type ListAuditAssignmentsRow struct {
	ID                 string      `json:"id"`
	InspectionID       string      `json:"inspection_id"`
	OrganizationID     string      `json:"organization_id"`
	LeadSubjectID      string      `json:"lead_subject_id"`
	Status             string      `json:"status"`
	ScheduledStartDate pgtype.Date `json:"scheduled_start_date"`
	ScheduledEndDate   pgtype.Date `json:"scheduled_end_date"`
	Revision           int64       `json:"revision"`
}

func (q *Queries) ListAuditAssignments(ctx context.Context, arg ListAuditAssignmentsParams) ([]ListAuditAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listAuditAssignments, arg.OrganizationID, arg.StatusFilter, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditAssignmentsRow
	for rows.Next() {
		var i ListAuditAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.InspectionID,
			&i.OrganizationID,
			&i.LeadSubjectID,
			&i.Status,
			&i.ScheduledStartDate,
			&i.ScheduledEndDate,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditQuestionAssignments = `-- name: ListAuditQuestionAssignments :many
SELECT assignment_id, question_id, subject_id, revision
FROM audit_question_assignments
WHERE assignment_id = $1
ORDER BY question_id, subject_id
`

type ListAuditQuestionAssignmentsRow struct {
	AssignmentID string `json:"assignment_id"`
	QuestionID   string `json:"question_id"`
	SubjectID    string `json:"subject_id"`
	Revision     int64  `json:"revision"`
}

func (q *Queries) ListAuditQuestionAssignments(ctx context.Context, assignmentID string) ([]ListAuditQuestionAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listAuditQuestionAssignments, assignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditQuestionAssignmentsRow
	for rows.Next() {
		var i ListAuditQuestionAssignmentsRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.QuestionID,
			&i.SubjectID,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditTeamMembers = `-- name: ListAuditTeamMembers :many
SELECT assignment_id, subject_id, member_role, revision
FROM audit_team_members
WHERE assignment_id = $1 AND removed_at IS NULL
ORDER BY member_role, subject_id
`

type ListAuditTeamMembersRow struct {
	AssignmentID string `json:"assignment_id"`
	SubjectID    string `json:"subject_id"`
	MemberRole   string `json:"member_role"`
	Revision     int64  `json:"revision"`
}

func (q *Queries) ListAuditTeamMembers(ctx context.Context, assignmentID string) ([]ListAuditTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listAuditTeamMembers, assignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditTeamMembersRow
	for rows.Next() {
		var i ListAuditTeamMembersRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.SubjectID,
			&i.MemberRole,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuditAssignment = `-- name: UpdateAuditAssignment :one
UPDATE audit_assignments
SET lead_subject_id = $2,
    status = $3,
    scheduled_start_date = $4,
    scheduled_end_date = $5,
    revision = revision + 1,
    updated_at = $6
WHERE id = $1 AND revision = $7 AND tombstoned_at IS NULL
RETURNING id, inspection_id, organization_id, lead_subject_id, status,
          scheduled_start_date, scheduled_end_date, revision
`

type UpdateAuditAssignmentParams struct {
	ID                 string             `json:"id"`
	LeadSubjectID      string             `json:"lead_subject_id"`
	Status             string             `json:"status"`
	ScheduledStartDate pgtype.Date        `json:"scheduled_start_date"`
	ScheduledEndDate   pgtype.Date        `json:"scheduled_end_date"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Revision           int64              `json:"revision"`
}

type UpdateAuditAssignmentRow struct {
	ID                 string      `json:"id"`
	InspectionID       string      `json:"inspection_id"`
	OrganizationID     string      `json:"organization_id"`
	LeadSubjectID      string      `json:"lead_subject_id"`
	Status             string      `json:"status"`
	ScheduledStartDate pgtype.Date `json:"scheduled_start_date"`
	ScheduledEndDate   pgtype.Date `json:"scheduled_end_date"`
	Revision           int64       `json:"revision"`
}

func (q *Queries) UpdateAuditAssignment(ctx context.Context, arg UpdateAuditAssignmentParams) (UpdateAuditAssignmentRow, error) {
	row := q.db.QueryRow(ctx, updateAuditAssignment,
		arg.ID,
		arg.LeadSubjectID,
		arg.Status,
		arg.ScheduledStartDate,
		arg.ScheduledEndDate,
		arg.UpdatedAt,
		arg.Revision,
	)
	var i UpdateAuditAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.InspectionID,
		&i.OrganizationID,
		&i.LeadSubjectID,
		&i.Status,
		&i.ScheduledStartDate,
		&i.ScheduledEndDate,
		&i.Revision,
	)
	return i, err
}
