// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PotentialFinding struct {
	ID                  string             `json:"id"`
	InspectionID        string             `json:"inspection_id"`
	ChecklistResponseID string             `json:"checklist_response_id"`
	OrganizationID      string             `json:"organization_id"`
	Status              string             `json:"status"`
	FindingBasis        string             `json:"finding_basis"`
	ExpectedEvidence    *string            `json:"expected_evidence"`
	CommentToAuditee    string             `json:"comment_to_auditee"`
	InternalCaaNote     *string            `json:"internal_caa_note"`
	ConvertedFindingID  *string            `json:"converted_finding_id"`
	Revision            int64              `json:"revision"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	QuestionID          string             `json:"question_id"`
	Title               string             `json:"title"`
	Description         string             `json:"description"`
	CreatedBySubjectID  string             `json:"created_by_subject_id"`
}
