// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"
)

const getPotentialFinding = `-- name: GetPotentialFinding :one
SELECT id, inspection_id, checklist_response_id, organization_id, status, finding_basis,
       expected_evidence, comment_to_auditee, internal_caa_note, converted_finding_id,
       revision, created_at, updated_at, question_id, title, description, created_by_subject_id
FROM potential_findings
WHERE id = $1
`

func (q *Queries) GetPotentialFinding(ctx context.Context, id string) (PotentialFinding, error) {
	row := q.db.QueryRow(ctx, getPotentialFinding, id)
	var i PotentialFinding
	err := row.Scan(
		&i.ID,
		&i.InspectionID,
		&i.ChecklistResponseID,
		&i.OrganizationID,
		&i.Status,
		&i.FindingBasis,
		&i.ExpectedEvidence,
		&i.CommentToAuditee,
		&i.InternalCaaNote,
		&i.ConvertedFindingID,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuestionID,
		&i.Title,
		&i.Description,
		&i.CreatedBySubjectID,
	)
	return i, err
}

const getPotentialFindingByResponse = `-- name: GetPotentialFindingByResponse :one
SELECT id, status, revision
FROM potential_findings
WHERE checklist_response_id = $1
`

type GetPotentialFindingByResponseRow struct {
	ID       string `json:"id"`
	Status   string `json:"status"`
	Revision int64  `json:"revision"`
}

func (q *Queries) GetPotentialFindingByResponse(ctx context.Context, checklistResponseID string) (GetPotentialFindingByResponseRow, error) {
	row := q.db.QueryRow(ctx, getPotentialFindingByResponse, checklistResponseID)
	var i GetPotentialFindingByResponseRow
	err := row.Scan(&i.ID, &i.Status, &i.Revision)
	return i, err
}

const getPotentialFindingForUpdate = `-- name: GetPotentialFindingForUpdate :one
SELECT id, inspection_id, checklist_response_id, organization_id, status, finding_basis,
       expected_evidence, comment_to_auditee, internal_caa_note, converted_finding_id,
       revision, created_at, updated_at, question_id, title, description, created_by_subject_id
FROM potential_findings
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetPotentialFindingForUpdate(ctx context.Context, id string) (PotentialFinding, error) {
	row := q.db.QueryRow(ctx, getPotentialFindingForUpdate, id)
	var i PotentialFinding
	err := row.Scan(
		&i.ID,
		&i.InspectionID,
		&i.ChecklistResponseID,
		&i.OrganizationID,
		&i.Status,
		&i.FindingBasis,
		&i.ExpectedEvidence,
		&i.CommentToAuditee,
		&i.InternalCaaNote,
		&i.ConvertedFindingID,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuestionID,
		&i.Title,
		&i.Description,
		&i.CreatedBySubjectID,
	)
	return i, err
}
