// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetPotentialFinding(ctx context.Context, id string) (PotentialFinding, error)
	GetPotentialFindingByResponse(ctx context.Context, checklistResponseID string) (GetPotentialFindingByResponseRow, error)
	GetPotentialFindingForUpdate(ctx context.Context, id string) (PotentialFinding, error)
}

var _ Querier = (*Queries)(nil)
